# Generated by Django 5.2.3 on 2025-07-06 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_newslettercontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslettercontent',
            name='author',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='newslettercontent',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='newsletter/'),
        ),
    ]
