# Generated by Django 5.2.3 on 2025-07-06 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0003_newslettercontent_author_newslettercontent_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewsletterContent',
            new_name='Newsletter',
        ),
    ]
