# Generated by Django 5.2.3 on 2025-07-06 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0004_rename_newslettercontent_newsletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
