# Generated by Django 5.2.3 on 2025-06-29 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('label', models.CharField(blank=True, max_length=50, null=True)),
                ('sqf', models.IntegerField(default=0)),
                ('beds', models.IntegerField(default=0)),
                ('baths', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='listings/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
