# Generated by Django 5.2.3 on 2025-07-08 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='sqf',
            new_name='size',
        ),
    ]
