# Generated by Django 5.2.3 on 2025-07-08 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0002_rename_sqf_listing_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='type',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
