# Generated by Django 5.2.3 on 2025-07-10 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0004_amenity_listing_amenities_listingimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='garage',
            field=models.IntegerField(default=0),
        ),
    ]
