# Generated by Django 5.2.3 on 2025-07-10 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0005_listing_garage'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='description',
            field=models.CharField(blank=True, null=True),
        ),
    ]
