# Generated by Django 5.2.3 on 2025-08-01 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='registered_via_api',
            field=models.BooleanField(default=True),
        ),
    ]
