# Generated by Django 5.2.3 on 2025-08-08 05:33

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userprofile_registered_via_api'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.user_profile_picture_path),
        ),
    ]
